---
- name: Add Docker repository key
  apt_key: url="https://get.docker.io/gpg" id="A88D21E9"

- name: Add Docker repository
  apt_repository:
    repo: 'deb http://get.docker.io/ubuntu docker main'
    update_cache: yes

- name: Install Docker
  apt: pkg=lxc-docker
  notify: "restart docker"

- name: Install python-pip
  apt: pkg=python-pip

- name: Install docker-py
  pip: name=docker-py

# - name: Check if /etc/default/ufw exists
#   stat: path=/etc/default/ufw
#   register: ufw_default_exists

# - name: Change ufw default forward policy from drop to accept
#   lineinfile:
#     dest=/etc/default/ufw
#     regexp="^DEFAULT_FORWARD_POLICY="
#     line="DEFAULT_FORWARD_POLICY=\"ACCEPT\""
#   when: ufw_default_exists.stat.exists

- name: Start docker
  service:
    name=docker
    state=started
