---
- name: Stop mesos-master
  service:
    name=mesos-master
    state=stopped
  when: mesos_master is defined and not mesos_master

- name: Disable mesos-master
  copy:
    dest=/etc/init/mesos-master.override
    content=manual
  when: mesos_master is defined and not mesos_master

- name: Stop zookeeper
  service:
    name=zookeeper
    state=stopped
  when: mesos_master is defined and not mesos_master

- name: Disable zookeeper
  copy:
    dest=/etc/init/zookeeper.override
    content=manual
  when: mesos_master is defined and not mesos_master

- name: Make sure mesos-slave is running
  service:
    name=mesos-slave
    state=running
